#! /bin/bash

infile="../entradas/input.json"
modelfile="Horario.mod"
modeldat="input.dat"
modelout="result.csv"
jsonout="result.json"
htmlfile="horarios.html"
outfolder="out"

function solve() {
    clean

    mkdir -p "$outfolder"
    py json2dat.py "$infile" "$outfolder/$modeldat"
    oplrun "$modelfile" "$outfolder/$modeldat"
    mv "$modelout" "$outfolder/$modelout"
    py csv2json.py "$outfolder/$modelout" "$outfolder/$jsonout"
    php horario.php "$outfolder/$jsonout" "$outfolder/$htmlfile"
}

function clean() {
    rm -rf "$outfolder"
}

# Set command to command line argument
command="$1"

# If that was empty, set it to "test"
: ${command:=solve}

# Run command
cd "$(dirname ${BASH_SOURCE[0]})"
eval "$command"
