#! /bin/bash

infile="../entradas/input.all.json"
modelfile="Horario.mod"
modeldat="input.dat"
modelout="result.csv"
jsonout="result.json"
htmlfile="horarios.html"
outfolder="out"

function solve() {
    clean

    mkdir -p "$outfolder"
    py json2dat.py "$infile" "$outfolder/$modeldat"
    oplrun "$modelfile" "$outfolder/$modeldat"
    OUT=$?
    if [ $OUT -ne 0 ] ; then
        echo "Erro na resolução do modelo. Encerrando."
        exit 1
    fi

    mv "$modelout" "$outfolder/$modelout"
    py csv2json.py "$outfolder/$modelout" "$outfolder/$jsonout"
    py horario.py "$outfolder/$jsonout" "$outfolder/$htmlfile"

    OUT=$?
    if [ $OUT -eq 0 ] ; then
        echo "Execução terminada com sucesso. Arquivos disponíveis em $outfolder/"
    fi
}

function clean() {
    rm -rf "$outfolder"
}

# Set command to command line argument
command="$1"

# If that was empty, set it to "test"
: ${command:=solve}

# Run command
cd "$(dirname ${BASH_SOURCE[0]})"
eval "$command"
